WorldMVC/Controllers/CitiesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using DataModel.IRepositories;
using DataModel.Models;
using Infrastructure.Repositories;
using Newtonsoft.Json;
using WorldMVC.ModelViews;

namespace WorldMVC.Controllers
{
    public class CitiesController : Controller
    {
        private IGeneric<City> _repo;
        private IGeneric<Country> _countryRepo;

        public CitiesController(IGeneric<City> repo, IGeneric<Country> countryRepo)
        {
            _repo = repo;
            _countryRepo = countryRepo;
        }

        // GET: CityController
        [HttpGet]
        public ActionResult Index()
        {
            return View();
        }
        public JsonResult CityAjex()
        {
            List<City> cities = _repo.RetriveAll();
            foreach (var city in cities)
            {
                city.Country = _countryRepo.RetriveById(city.CountryId);
            }

            return Json(cities, JsonRequestBehavior.AllowGet);
        }

        // GET: CityController/Details/5
        public ActionResult Details(int id)
        {
            City city = _repo.RetriveById(id);
            return View(city);
        }

        // GET: CityController/Create
        public ActionResult Create()
        {
            List<Country> countries = _countryRepo.RetriveAll();
            CountryCityVM countryCityVM = new CountryCityVM
            {
                Countries = countries
            };
            return View(countryCityVM);
        }

        // POST: CityController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(CountryCityVM countryCityVM)
        {
            try
            {
                City city = new City
                {
                    CityName = countryCityVM.City.CityName,
                    CountryId = countryCityVM.City.CountryId
                };
                _repo.Create(city);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: CityController/Edit/5
        public ActionResult Edit(int id)
        {
            City city = _repo.RetriveById(id);
            List<Country> countries = _countryRepo.RetriveAll();
            CountryCityVM countryCityVM = new CountryCityVM
            {
                City = city,
                Countries = countries
            };
            return View(countryCityVM);
        }

        // POST: CityController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(CountryCityVM countryCityVM)
        {
            try
            {
                City city = new City
                {
                    Id = countryCityVM.City.Id,
                    CityName = countryCityVM.City.CityName,
                    CountryId = countryCityVM.City.CountryId
                };
                _repo.Patch(city);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: CityController/Delete/5
        public ActionResult Delete(int id)
        {
            City city = _repo.RetriveById(id);
            return View(city);
        }

        // POST: CityController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            try
            {
                _repo.Delete(id);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

WorldMVC/Controllers/CountriesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using DataModel.Models;
using Infrastructure.Repositories;
using Microsoft.Ajax.Utilities;

namespace WorldMVC.Controllers
{
    public class CountriesController : Controller
    {
        private CountryRepo _repo;

        public CountriesController(CountryRepo repo)
        {
            _repo = repo;
        }
        public ActionResult Index()
        {
            return View();
        }
        public JsonResult CountryAjex()
        {
            List<Country> countries = _repo.RetriveAll();
            return Json(countries,JsonRequestBehavior.AllowGet);
        }

        // GET: CountryController/Details/5
        public ActionResult Details(int id)
        {
            Country country = _repo.RetriveById(id);
            return View(country);
        }

        // GET: CountryController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: CountryController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Country country)
        {
            try
            {
                _repo.Create(country);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: CountryController/Edit/5
        public ActionResult Edit(int id)
        {
            Country country = _repo.RetriveById(id);
            return View(country);
        }

        // POST: CountryController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Country country)
        {
            try
            {
                _repo.Patch(country);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: CountryController/Delete/5
        public ActionResult Delete(int id)
        {
            Country country = _repo.RetriveById(id);
            return View(country);
        }

        // POST: CountryController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            try
            {
                _repo.Delete(id);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

    }
}

WorldMVC/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WorldMVC.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }
        public ActionResult About2()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

WorldMVC/Views/Cities/Create.cshtml
@model WorldMVC.ModelViews.CountryCityVM

@{
    ViewBag.Title = "Create";
}

<h2 class="text-center text-success">Create City</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.City.CityName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.City.CityName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.City.CityName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2"> Country</label>
            <div class="col-md-10">
                @Html.DropDownList("City.CountryId", new SelectList(Model.Countries, "Id", "CountryName"), htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.City.CountryId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

WorldMVC/Views/Cities/Delete.cshtml
@model DataModel.Models.City

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>City</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.CityName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CityName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AddedDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AddedDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Country.CountryName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Country.CountryName)
        </dd>

    </dl>

    @using (Html.BeginForm("DeleteConfirmed", "Cities"))
    {

        @Html.AntiForgeryToken()

<div class="form-actions no-color">
    @Html.HiddenFor(model => model.Id)
    <input type="submit" value="Delete" class="btn btn-default" /> |
    @Html.ActionLink("Back to List", "Index")
</div>
    }
</div>

WorldMVC/Views/Cities/Details.cshtml
@model DataModel.Models.City

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>City</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.CityName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CityName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AddedDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AddedDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Country.CountryName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Country.CountryName)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

WorldMVC/Views/Cities/Edit.cshtml
@model WorldMVC.ModelViews.CountryCityVM
@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>City</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.City.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.City.CityName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.City.CityName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.City.CityName, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <label class="control-label col-md-2"> Country</label>
            <div class="col-md-10">
                @Html.DropDownList("City.CountryId", new SelectList(Model.Countries, "Id", "CountryName"), htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.City.CountryId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

WorldMVC/Views/Cities/Index.cshtml
@model IEnumerable<DataModel.Models.City>

@{
    ViewBag.Title = "Index";
}

<h2 class="text-center text-success">Cities</h2>

<p  style="margin:15px;">
    @Html.ActionLink("Create New", "Create",null ,new {@class ="btn btn-success" })
</p>
<div class="row">
    <div class="col-md-12">

        <table id="citytbl" class="table">
        </table>
    </div>
</div>
@section Styles{
    <link href="~/Content/bootstrap.css" rel="stylesheet" />
    <link href="https://cdn.datatables.net/1.10.15/css/dataTables.bootstrap.min.css" rel="stylesheet" />
    <link href="https://cdn.datatables.net/responsive/2.1.1/css/responsive.bootstrap.min.css" rel="stylesheet" />
}
@section Scripts{
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.15/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.15/js/dataTables.bootstrap4.min.js "></script>
    <script src="~/Scripts/app/City.js"></script>
}

WorldMVC/Views/Countries/Create.cshtml
@model DataModel.Models.Country

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Country</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.CountryName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CountryName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CountryName, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

WorldMVC/Views/Countries/Delete.cshtml
@model DataModel.Models.Country

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Country</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.CountryName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CountryName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AddedDateTime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AddedDateTime)
        </dd>

    </dl>

    @using (Html.BeginForm("DeleteConfirmed","Countries")) {
        @Html.AntiForgeryToken()

<div class="form-actions no-color">
    @Html.HiddenFor(model => model.Id)
    <input type="submit" value="Delete" class="btn btn-default" /> |
    @Html.ActionLink("Back to List", "Countries", "Index")
</div>
    }
</div>

WorldMVC/Views/Countries/Details.cshtml
@model DataModel.Models.Country

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Country</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.CountryName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CountryName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AddedDateTime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AddedDateTime)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

WorldMVC/Views/Countries/Edit.cshtml
@model DataModel.Models.Country

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Country</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.CountryName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CountryName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CountryName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

WorldMVC/Views/Countries/Index.cshtml
@{
    ViewBag.Title = "Index";
}


<h2 class="text-center text-success">Countries</h2>


<p>
    @Html.ActionLink("Create New", "Create", null, new { @class = "btn btn-success" })
</p>
<div class="row">
    <div class="col-md-12">

        <table id="countrytbl" class="table">
        </table>
    </div>
</div>



@section Styles{
    <link href="~/Content/bootstrap.css" rel="stylesheet" />
    <link href="https://cdn.datatables.net/1.10.15/css/dataTables.bootstrap.min.css" rel="stylesheet" />
    <link href="https://cdn.datatables.net/responsive/2.1.1/css/responsive.bootstrap.min.css" rel="stylesheet" />
}
@section Scripts{
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.15/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.15/js/dataTables.bootstrap4.min.js "></script>
    <script src="~/Scripts/app/Country.js"></script>
}

WorldMVC/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

WorldMVC/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

WorldMVC/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

WorldMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("World", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Countries", "Index", "Countries")</li>
                    <li>@Html.ActionLink("Cities", "Index", "Cities")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - By Hagar Metwalli</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("Styles", required: false)
    @RenderSection("Scripts", required: false)
</body>
</html>